# DO NOT modify this file

ifdef KRN_TARGET_PROJECT
include $(KRN_PROJECT_FOLDER)/BoardConfig-kernel.mk
endif#KRN_TARGET_PROJECT
ifdef HAL_TARGET_PROJECT
include $(HAL_PROJECT_FOLDER)/BoardConfig.mk
endif#HAL_TARGET_PROJECT
ifdef VEXT_TARGET_PROJECT
include $(VEXT_PROJECT_FOLDER)/BoardConfig-vext.mk
MTK_SPLIT_BOARD_RECOVERY_KERNEL_MODULES                     := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_RECOVERY_KERNEL_MODULES))
MTK_SPLIT_BOARD_RECOVERY_KERNEL_MODULES_LOAD                := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_RECOVERY_KERNEL_MODULES_LOAD))
MTK_SPLIT_BOARD_VENDOR_RAMDISK_KERNEL_MODULES               := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_VENDOR_RAMDISK_KERNEL_MODULES))
MTK_SPLIT_BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD          := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD))
MTK_SPLIT_BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD))
MTK_SPLIT_BOARD_VENDOR_KERNEL_MODULES                       := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_VENDOR_KERNEL_MODULES))
MTK_SPLIT_BOARD_VENDOR_KERNEL_MODULES_LOAD                  := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_VENDOR_KERNEL_MODULES_LOAD))
MTK_SPLIT_BOARD_ODM_KERNEL_MODULES                          := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_ODM_KERNEL_MODULES))
MTK_SPLIT_BOARD_ODM_KERNEL_MODULES_LOAD                     := $(patsubst $(KERNEL_OUT)/%,%,$(BOARD_ODM_KERNEL_MODULES_LOAD))
ifndef KRN_TARGET_PROJECT
BOARD_RECOVERY_KERNEL_MODULES       :=
BOARD_VENDOR_RAMDISK_KERNEL_MODULES :=
BOARD_VENDOR_KERNEL_MODULES         :=
BOARD_ODM_KERNEL_MODULES            :=
endif#KRN_TARGET_PROJECT
endif#VEXT_TARGET_PROJECT

include device/mediatek/build/core/soong_config.mk

# DO NOT modify this file
