SYS_TARGET_PROJECT := mssi_64_cn_armv82
SYS_TARGET_PROJECT_FOLDER := device/mediatek/system/$(SYS_TARGET_PROJECT)
VND_TARGET_PROJECT := k6895v1_64
VND_TARGET_PROJECT_FOLDER := $(LOCAL_PATH)

include $(SYS_TARGET_PROJECT_FOLDER)/sys_$(SYS_TARGET_PROJECT).mk
include $(VND_TARGET_PROJECT_FOLDER)/vnd_$(VND_TARGET_PROJECT).mk

PRODUCT_NAME := full_k6895v1_64
