BUILD_LK = yes
BUILD_PRELOADER = yes
CUSTOM_CONFIG_MAX_DRAM_SIZE = 0x800000000
CUSTOM_HAL_IMGSENSOR = s5kjd1_mipi_raw ov05a20_mipi_raw imx519_mipi_raw imx586_mipi_raw imx576_mipi_raw imx398_mipi_raw imx350_mipi_raw s5k2l7_mipi_raw imx386_mipi_raw imx481_mipi_raw s5k2t7sp_mipi_raw imx499_mipi_raw imx319_mipi_raw s5k3m5sx_mipi_raw gc02m0_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = s5kjd1_mipi_raw ov05a20_mipi_raw imx519_mipi_raw imx586_mipi_raw imx576_mipi_raw imx398_mipi_raw imx350_mipi_raw s5k2l7_mipi_raw imx386_mipi_raw imx481_mipi_raw s5k2t7sp_mipi_raw imx499_mipi_raw imx319_mipi_raw s5k3m5sx_mipi_raw gc02m0_mipi_raw
#ifdef OPLUS_FEATURE_MODEM
#Luoyuchun@NETWORK.MODEM, fix for custom modem
CUSTOM_MODEM = oplus6895_ALL
#endif OPLUS_FEATURE_MODEM
KEYMASTER_VERSION = 5.0
LINUX_KERNEL_VERSION = kernel-5.10
MICROTRUST_TEE_SUPPORT = no
MTK_A2DP_OFFLOAD_SUPPORT = yes
MTK_AB_OTA_UPDATER = yes
MTK_AEE_SUPPORT = yes
MTK_AI_SCENE_PQ_SUPPORT = no
MTK_APP_RESOLUTION_TUNER_SUPPORT = no
MTK_APUSYS_EDMA_SUPPORT = yes
MTK_APUSYS_MDLA_SUPPORT = yes
MTK_APUSYS_RT_SUPPORT = yes
MTK_APUSYS_SUPPORT = yes
MTK_ARC_GIFT_SUPPORT = yes
MTK_AUDIO_HYBRID_NLE_SUPPORT = no
MTK_AUDIO_MIC_INVERSE = no
MTK_AUDIO_NUMBER_OF_MIC = 2
MTK_AUDIO_NUMBER_OF_SPEAKER = 1
MTK_AUDIO_SPEAKER_PATH = smartpa_richtek_rt5512
MTK_AUDIO = yes
MTK_BACKLIGHT_SMOOTH_SUPPORT = no
MTK_BASIC_PACKAGE = no
MTK_BESLOUDNESS_RUN_WITH_HAL = yes
MTK_BESLOUDNESS_SUPPORT =no
MTK_BSP_PACKAGE = yes
MTK_BT_CHIP = MTK_CONSYS_MT6895
MTK_BT_DEFAULT_OFF = no
MTK_BT_INTEROP_EXTENSION = yes
MTK_BT_SAP_ENABLE = yes
MTK_CALTM_SUPPORT = no
MTK_CAM_EIS_SUPPORT = yes
MTK_CAMERA_APP_VERSION = 3
MTK_CAM_SECURE_FD_SUPPORT = yes
MTK_CAM_VHDR_SUPPORT = yes
MTK_CAM_VPU_DSDN = no
MTK_COMBO_CHIP = CONSYS_6895
MTK_COMBO_SUPPORT = yes
MTK_CONNSYS_DEDICATED_LOG_PATH = yes
MTK_CONSYS_EFEM_SUPPORT = no
MTK_CONSYSLOGGER_SUPPORT = yes
MTK_CTA_SET = MSSI only
MTK_DISABLE_CAPABILITY_SWITCH = no
MTK_DISPLAY_CUTOUT_POLICY = 5
MTK_DMC_SUPPORT = no
MTK_DM_VERITY_OFF = no
MTK_DPM_SUPPORT = yes
MTK_DRM_APP = no
MTK_DUAL_CHARGER_SUPPORT = no
MTK_DUAL_MIC_SUPPORT = yes
MTK_DURASPEED_DEFAULT_ON = yes
MTK_DURASPEED_SUPPORT = yes
#ifdef OPLUS_FEATURE_MODEM
#Luoyuchun@NETWORK.DATA.2899389, 2022/01/25, add for ap_md_c_smem optimization
#MTK_DYNAMIC_CCB_BUFFER_GEAR_ID =
#else
MTK_DYNAMIC_CCB_BUFFER_GEAR_ID = 4
#endif /* OPLUS_FEATURE_MODEM */
MTK_DYNAMIC_KERNEL_LOADING = no
MTK_DYNAMIC_PARTITION_SUPPORT = yes
MTK_DYNAMIC_SBP_LEVEL = 3
MTK_DYNAMIC_SBP_SUPPORT = yes
MTK_EFUSE_WRITER_SUPPORT = no
MTK_EMMC_SUPPORT_OTP = yes
MTK_EMMC_SUPPORT = yes
MTK_ENABLE_GENIEZONE = yes
MTK_ENABLE_HWASAN = no
MTK_ENABLE_NATIVE_ASAN = no
MTK_ENCRYPTION_DEFAULT_OFF = no
MTK_ENCRYPTION_FDE_TO_FBE = no
MTK_ENCRYPTION_TYPE_FILE = yes
MTK_FACTORY_MODE_IN_GB2312 = yes
MTK_FACTORY_RESET_PROTECTION_SUPPORT = yes
MTK_FEMTO_CELL_SUPPORT = no
MTK_FLIGHT_MODE_POWER_OFF_MD = no
MTK_FM_50KHZ_SUPPORT = no
MTK_FM_SHORT_ANTENNA_SUPPORT = no
MTK_GAUGE_VERSION = 30
MTK_GLT_SUPPORT = 1
MTK_GMO_RAM_OPTIMIZE = no
MTK_GMO_ROM_OPTIMIZE = no
MTK_GPT_SCHEME_SUPPORT = yes
MTK_GPU_COMMON_DVFS_SUPPORT = yes
MTK_GPU_SUPPORT = yes
MTK_GPU_VERSION = mali valhall r32p1
#ifdef OPLUS_FEATURE_GAMESPACE_MT_OPTIMIZATION
#Qixin.XIANG@NETWORK.DATA.454034, 2020/09/27, add for open mtk gwsd
#MTK_GWSD_V2_SUPPORT = no
#else
MTK_GWSD_V2_SUPPORT = yes
#endif /* OPLUS_FEATURE_GAMESPACE_MT_OPTIMIZATION */
MTK_GZ_RKP_SUPPORT = no
MTK_GZ_SUPPORT_SDSP = no
MTK_HIDL_PROCESS_CONSOLIDATION_ENABLED = no
MTK_HIFIAUDIO_SUPPORT = yes
MTK_HIGH_FRAME_RATE_DEFAULT_FPS = 120
MTK_HW_ENHANCE = no
MTK_INCALL_HANDSFREE_DMNR = no
MTK_K64_SUPPORT = yes
MTK_LK_VERSION = lk2
MTK_LOG_CUSTOMER_SUPPORT = yes
MTK_LOG_SUPPORT_GPS = yes
MTK_MCIF_WIFI_SUPPORT = yes
MTK_MDDP_WH_SUPPORT = no
MTK_MDLOGGER_SUPPORT = yes
MTK_MOBILE_MANAGEMENT = yes
MTK_MODEM_MONITOR_SUPPORT = yes
MTK_MPE_SUPPORT = yes
MTK_MULTIPLE_IMS_SUPPORT = 2
MTK_NEBULA_VM_SUPPORT = no
MTK_NETWORK_LOG_SUPPORT = yes
MTK_NFC_GSMA_SUPPORT = no
MTK_NN_SDK_SUPPORT = yes
MTK_NWK_OPT_SUPPORT = yes
MTK_OMADM_SUPPORT = no
MTK_OVERRIDES_APKS = yes
MTK_PAPE = 1
MTK_PLATFORM = MT6895
MTK_PLATFORM_OPTIMIZE = yes
MTK_PQ_COLOR_MODE = DISP_MDP
MTK_PQ_SUPPORT = PQ_HW_VER_2
MTK_PQ_VIDEO_WHITELIST_SUPPORT = no
MTK_PRODUCT_LINE_PLATFORM = no
MTK_PRODUCT_LINE = smart_phone
MTK_PROJECT_DTB_NAMES = mediatek/oplus6895_21861 mediatek/oplus6895_21641_EVT mediatek/oplus6895_21642_EVT mediatek/oplus6895_21121 mediatek/oplus6895_21861_T0 mediatek/oplus6895_21143 mediatek/oplus6895_21641 mediatek/oplus6895_21642 mediatek/oplus6895_21863 mediatek/oplus6895_22801
MTK_PROTOCOL1_RAT_CONFIG = N/C/Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = N/L/W/G
MTK_PROTOCOL3_RAT_CONFIG = G
MTK_PUMP_EXPRESS_PLUS_20_SUPPORT = no
MTK_PUMP_EXPRESS_PLUS_SUPPORT = no
MTK_RADIOOFF_POWER_OFF_MD = no
MTK_RCS_UA_SUPPORT = no
MTK_REFRSH_RATE_SPECIFIC_APP_FPS = no
MTK_RILD_READ_IMSI = yes
MTK_SCLTM_SUPPORT = yes
MTK_SEC_VIDEO_PATH_SUPPORT = no
MTK_SIGNATURE_CUSTOMIZATION = no
MTK_SIM_CARD_ONOFF = 3
#ifdef OPLUS_BUG_STABILITY
#HEZELIN@NETWORK.SIM.2958556, 2022/01/10, Add for sim hot plug
#MTK_SIM_HOT_SWAP_COMMON_SLOT = no
MTK_SIM_HOT_SWAP_COMMON_SLOT = yes
#endif /* OPLUS_BUG_STABILITY */
MTK_SIM_LOCK_POWER_ON_WRITE_PROTECT = no
MTK_SINGLE_BIN_MODEM_SUPPORT = yes
MTK_SMART_SWITCH_SUPPORT = no
MTK_TC1_COMMON_SERVICE = no
MTK_TC1_FEATURE = no
#ifdef OPLUS_FEATURE_SECURITY_COMMON
#Meilin.Zhou@BSP.Security.Basic, 2021/08/10, add for open trustonic tee, config tee.
MTK_ATF_SUPPORT = yes
MTK_TEE_SUPPORT = yes
MTK_TEE_GP_SUPPORT = yes
TRUSTONIC_TEE_SUPPORT = yes
MTK_PERSIST_PARTITION_SUPPORT = yes
#endif /* OPLUS_FEATURE_SECURITY_COMMON */
MTK_TEE_TRUSTED_UI_SUPPORT = no
MTK_TER_SERVICE = no
MTK_TINYSYS_MCUPM_SUPPORT = yes
MTK_TINYSYS_SCP_LOGGER_SUPPORT = yes
MTK_TINYSYS_SCP_SUPPORT = yes
MTK_TINYSYS_SSPM_SUPPORT = yes
MTK_TOUCH_KO = GT9886 GT9896S
MTK_TOUCHPANEL_FIRMWARE = GT9886 GT9896S NT36672C
MTK_UFS_OTP = yes
MTK_UFS_SUPPORT = yes
MTK_ULTRASND_PROXIMITY = yes
MTK_USER_SPACE_DEBUG_FW = yes
MTK_V4L2_INTERFACE = yes
MTK_VIDEO_TRANSITION = no
MTK_VOIP_HANDSFREE_DMNR = no
MTK_VOW_AMAZON_SUPPORT = no
MTK_VOW_DSP_VERSION = ver02
MTK_VOW_DUAL_MIC_SUPPORT = yes
MTK_VOW_BARGE_IN_SUPPORT = yes
MTK_VOW_GVA_SUPPORT = no
MTK_VOW_MAX_PDK_NUMBER = 2
MTK_VOW_SUPPORT = yes
MTK_VPU_SUPPORT = no
MTK_WAPI_SUPPORT = yes
MTK_WFD_SUPPORT = yes
MTK_WIFI_DUAL_BAND_SUPPORT = yes
MTK_WLAN_CHIP = CONSYS_MT6893
MTK_WORLD_PHONE_POLICY = 0
#ifdef OPLUS_FEATURE_SECURITY_COMMON
#Shengwang.Luo@BSP.Security.Basic, 2021/12/20, add for widevine L1
MTK_SEC_VIDEO_PATH_SUPPORT = yes
MTK_WVDRM_SUPPORT = yes
MTK_WVDRM_L1_SUPPORT = yes
MTK_DRM_KEY_MNG_SUPPORT = yes
#endif /* OPLUS_FEATURE_SECURITY_COMMON */
OPTR_SPEC_SEG_DEF = NONE
SIM_ME_LOCK_MODE = 3
SPM_FW_USE_PARTITION = yes
MTK_TFA_VERSION = tf-a-2.4
MTK_TEST_IT = yes
MTK_TEST_COV_LINE = no
MTK_TEST_AIT = yes
MTK_TEST_ST = yes
MTK_PLATFORM_DTB_NAME = mediatek/mt6895
MTK_TEST_UT = yes
MTK_DS_SUPPORT = yes
MTK_ULTRA_RESOLUTION_SUPPORT = no
MTK_DC_SUPPORT = no
MTK_CLEARZOOM_SUPPORT = no
MTK_DISP_CCORR_SUPPORT = yes
MTK_DISP_COLOR_SUPPORT = yes
MTK_DISP_GAMMA_SUPPORT = yes
MTK_HFG_SUPPORT = no
MTK_GENERIC_HAL = yes
MTK_CAM_ISPHIDL_SUPPORT = yes
MTK_DX_HDCP_SUPPORT = no
MTK_APUSYS_TINYSYS_SUPPORT = yes
MTK_AUDIO_A2DP_LATENCY_IMPROVE = yes
CUSTOM_KERNEL_STEP_DETECTOR = yes
MTK_AI_SDR_TO_HDR_SUPPORT = yes
MTK_PQ_INTERFACE_SUPPORT = yes
MTK_MML_SUPPORT = yes
MTK_VPU2_SUPPORT = yes
MKP_SERVICE_SUPPORT = yes
MTK_CUVA_HDR_SUPPORT = yes
MTK_NN_AI_CAM_SUPPORT = yes
MTK_TINYSYS_VCP_SUPPORT = yes
MTK_C2_SERVICE_DISABLED = no
MTK_C2_SERVICE_64_BIT = yes
MTK_GAMEHDR_SUPPORT = no
MTK_KEYMINT_VERSION = 0.0
#DISPLAY.FEATURE.AOD,2021/09/17,Add for AOD
MTK_AOD_SUPPORT = yes
MTK_RAY_TRACING_SUPPORT = no
MTK_AUDIO_TUNING_TOOL_VERSION = V2.2
MTK_PHONE_CALL_FIXED_48K_SAMPLERATE = yes
MTK_AUDIODSP_SUPPORT = yes
#ifdef OPLUS_BUG_STABILITY
#YuanMiao@NETWORK.SIM.2861838, 2022/01/04, Add for VSIM enable
MTK_EXTERNAL_SIM_SUPPORT = yes
#endif /* OPLUS_BUG_STABILITY */
MTK_FAST_CHARGER_TECH = yes
MTK_GAME_AISR_SUPPORT = no
MTK_TINYSYS_GPUEB_SUPPORT = yes
BOOT_LOGO = fhdplus2412
MTK_GPU_TUNER = yes
CUSTOM_KERNEL_ACCELEROMETER = yes
CUSTOM_KERNEL_ALSPS = yes
CUSTOM_KERNEL_BAROMETER = yes
CUSTOM_KERNEL_GYROSCOPE = yes
MTK_SENSOR_SUPPORT = yes
CUSTOM_KERNEL_MAGNETOMETER = yes
CUSTOM_KERNEL_STEP_COUNTER = yes
CUSTOM_HIFI_SENSORS = yes
MTK_KO_ORDER_TABLE_CHECK = VENDOR_RAMDISK
MTK_FD_SUPPORT = yes
MTK_GPS_SUPPORT = yes
MTK_AGPS_APP = yes
MTK_SLOW_MOTION_VIDEO_SUPPORT = yes
MTK_AAL_SUPPORT = yes
#linzhenghe@MM.Display.LCD, 2022/3 add MTK_DRE30_SUPPORT for aal-dre30 backlight
MTK_DRE30_SUPPORT = no
MTK_BLULIGHT_DEFENDER_SUPPORT = no
MTK_DISP_TDSHP_SUPPORT = yes
MTK_DISP_C3D_SUPPORT = yes
MTK_HDR10PLUS_ADAPTIVE_SUPPORT = no
MTK_CAM_FD_SUPPORT = yes
MTK_CAM_SECURITY_SUPPORT = yes
MTK_CAM_GENIEZONE_SUPPORT = yes
ARM_MTE_SUPPORT = no
MTK_VPU2_SECURITY_SUPPORT = no
MTK_NUM_MODEM_PROTOCOL = 2
MTK_HDR_VIDEO_SUPPORT = yes
MTK_SECURE_HEVC_VIDEO_SUPPORT_TABLET = no
#MTK_VOW_BARGE_IN_SUPPORT = yes
MTK_ANDROID_WIDE_GAMUT_DISPLAY = yes
MTK_HDR10_PLUS_RECORDING = yes
MTK_BLUETOOTH_LDAC_ABR = yes
#ifdef OPLUS_DYNAMIC_SINGLE_SIM
#Wei.Peng@NETWORK.SIM.2348909,2021/10/20
#Add for control dyanmic sim switch feature for different platform
OPLUS_DYNAMIC_SINGLE_SIM_SUPPORT = yes
#endif /*OPLUS_FEATURE_DYNAMIC_SINGLESIM*/
